providers = ["python"]

[phases.setup]
nixPkgs = ["pkgs.python311"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"

[phases.install]
cmds = ["uv sync --all-packages"]

[start]
cmd = "uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT"