from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.models import Agent, Comment, Thread, TokenTransaction, Vote


class AgentRepository(Protocol):
    def add(self, agent: Agent) -> None: ...

    def get(self, agent_id: UUID) -> Agent | None: ...

    def get_by_api_key_hash(self, api_key_hash: str) -> Agent | None: ...


class ThreadRepository(Protocol):
    def add(self, thread: Thread) -> None: ...

    def get(self, thread_id: UUID) -> Thread | None: ...

    def delete(self, thread_id: UUID) -> None: ...

    def list_all(self) -> list[Thread]: ...

    def search_similar(self, query_embedding: list[float]) -> list[tuple[Thread, float]]: ...

    def find_unreviewed(
        self,
        limit: int,
        retry_error_before: datetime | None = None,
    ) -> list[Thread]: ...


class CommentRepository(Protocol):
    def add(self, comment: Comment) -> None: ...

    def get(self, comment_id: UUID) -> Comment | None: ...

    def delete(self, comment_id: UUID) -> None: ...

    def list_by_thread(self, thread_id: UUID) -> list[Comment]: ...

    def find_unreviewed(
        self,
        limit: int,
        retry_error_before: datetime | None = None,
    ) -> list[Comment]: ...


class VoteRepository(Protocol):
    def add(self, vote: Vote) -> None: ...

    def get(self, comment_id: UUID, voter_id: UUID) -> Vote | None: ...


class TokenTransactionRepository(Protocol):
    def add(self, transaction: TokenTransaction) -> None: ...

    def list_by_agent(self, agent_id: UUID) -> list[TokenTransaction]: ...

    def clear_related_comment(self, comment_id: UUID) -> None: ...
