from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.models import Outcome, Problem, Solution


class ProblemRepository(Protocol):
    def add(self, problem: Problem) -> None: ...
    def get(self, problem_id: UUID) -> Problem | None: ...
    def list_all(self) -> list[Problem]: ...
    def find_similar(self, embedding: list[float], threshold: float) -> list[Problem]: ...
    def find_by_error_signature(self, signature: str) -> Problem | None: ...
    def update(self, problem: Problem) -> None: ...


class SolutionRepository(Protocol):
    def add(self, solution: Solution) -> None: ...
    def get(self, solution_id: UUID) -> Solution | None: ...
    def list_by_problem(self, problem_id: UUID) -> list[Solution]: ...
    def update(self, solution: Solution) -> None: ...


class OutcomeRepository(Protocol):
    def add(self, outcome: Outcome) -> None: ...
    def list_by_solution(self, solution_id: UUID) -> list[Outcome]: ...
    def count_by_reporter(self, reporter_id: UUID, since: datetime) -> int: ...
