"""add review fields to threads and comments

Revision ID: 1891b48a0ace
Revises: 20260204_0001
Create Date: 2026-02-05 17:23:04.221518
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1891b48a0ace'
down_revision = '20260204_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('review_status', sa.String(length=20), nullable=True))
    op.add_column('comments', sa.Column('review_score', sa.Float(), nullable=True))
    op.drop_index('idx_comments_path_gist', table_name='comments', postgresql_using='gist')
    op.drop_index('idx_comments_wilson', table_name='comments')
    op.add_column('threads', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threads', sa.Column('review_status', sa.String(length=20), nullable=True))
    op.add_column('threads', sa.Column('review_score', sa.Float(), nullable=True))
    op.drop_index('idx_threads_embedding', table_name='threads', postgresql_using='ivfflat')
    op.drop_index('idx_votes_comment_voter', table_name='votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_votes_comment_voter', 'votes', ['comment_id', 'voter_id'], unique=False)
    op.create_index('idx_threads_embedding', 'threads', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.drop_column('threads', 'review_score')
    op.drop_column('threads', 'review_status')
    op.drop_column('threads', 'reviewed_at')
    op.create_index('idx_comments_wilson', 'comments', ['wilson_score'], unique=False)
    op.create_index('idx_comments_path_gist', 'comments', ['path'], unique=False, postgresql_using='gist')
    op.drop_column('comments', 'review_score')
    op.drop_column('comments', 'review_status')
    op.drop_column('comments', 'reviewed_at')
    # ### end Alembic commands ###
