"""add v2 resolution graph tables

Revision ID: bdf1f1e79252
Revises: 1891b48a0ace
Create Date: 2026-02-20 10:45:15.998365
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    Vector = None

revision = "bdf1f1e79252"
down_revision = "1891b48a0ace"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    embedding_type = sa.JSON()
    vector_enabled = False

    if bind.dialect.name == "postgresql":
        available_extensions = {
            row[0]
            for row in bind.execute(
                sa.text("SELECT name FROM pg_available_extensions")
            ).fetchall()
        }
        if "vector" in available_extensions:
            op.execute("CREATE EXTENSION IF NOT EXISTS vector")
            vector_enabled = True
        if Vector is not None and vector_enabled:
            embedding_type = Vector(1536)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problems_v2",
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("error_signature", sa.Text(), nullable=True),
        sa.Column(
            "environment",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("embedding", embedding_type, nullable=True),
        sa.Column("best_confidence", sa.Float(), nullable=False),
        sa.Column("solution_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["agents.agent_id"],
        ),
        sa.PrimaryKeyConstraint("problem_id"),
    )
    op.create_index(
        op.f("ix_problems_v2_error_signature"),
        "problems_v2",
        ["error_signature"],
        unique=False,
    )

    if bind.dialect.name == "postgresql" and Vector is not None and vector_enabled:
        op.execute(
            "CREATE INDEX ix_problems_v2_embedding ON problems_v2 "
            "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
        )

    op.create_table(
        "solutions_v2",
        sa.Column("solution_id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("author_verified", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("outcome_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("environment_scores", sa.JSON(), nullable=False),
        sa.Column("canonical_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["agents.agent_id"],
        ),
        sa.ForeignKeyConstraint(
            ["canonical_id"],
            ["solutions_v2.solution_id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"], ["problems_v2.problem_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("solution_id"),
    )
    op.create_index(
        op.f("ix_solutions_v2_problem_id"), "solutions_v2", ["problem_id"], unique=False
    )
    op.create_table(
        "outcomes_v2",
        sa.Column("outcome_id", sa.String(length=36), nullable=False),
        sa.Column("solution_id", sa.String(length=36), nullable=False),
        sa.Column("reporter_id", sa.String(length=36), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "environment",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("error_after", sa.Text(), nullable=True),
        sa.Column("time_saved_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["agents.agent_id"],
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"], ["solutions_v2.solution_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("outcome_id"),
    )
    op.create_index(
        op.f("ix_outcomes_v2_solution_id"), "outcomes_v2", ["solution_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outcomes_v2_solution_id"), table_name="outcomes_v2")
    op.drop_table("outcomes_v2")
    op.drop_index(op.f("ix_solutions_v2_problem_id"), table_name="solutions_v2")
    op.drop_table("solutions_v2")
    op.drop_index(op.f("ix_problems_v2_error_signature"), table_name="problems_v2")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql" and Vector is not None:
        op.execute("DROP INDEX IF EXISTS ix_problems_v2_embedding")

    op.drop_table("problems_v2")
    # ### end Alembic commands ###
