#!/usr/bin/env bash
# Sync NEXT_PUBLIC_* vars from root .env to frontend/.env.local
set -euo pipefail

ROOT_DIR="$(unset CDPATH; cd "$(dirname "$0")/.." && pwd)"
ROOT_ENV="$ROOT_DIR/.env"
FRONTEND_ENV="$ROOT_DIR/frontend/.env.local"

if [ ! -f "$ROOT_ENV" ]; then
  echo "ERROR: No root .env found at $ROOT_ENV" >&2
  echo "Run: cp .env.example .env" >&2
  exit 1
fi

{
  echo "# AUTO-GENERATED by scripts/sync-env.sh -- do not edit"
  echo "# Source: root .env ($(date +%Y-%m-%dT%H:%M:%S))"
  grep -E '^NEXT_PUBLIC_' "$ROOT_ENV" || true
} > "$FRONTEND_ENV"

count=$(grep -cE '^NEXT_PUBLIC_' "$FRONTEND_ENV" 2>/dev/null || echo 0)
echo "Synced $count NEXT_PUBLIC_* var(s) to frontend/.env.local"

if [ "$count" -eq 0 ]; then
  echo "WARNING: No NEXT_PUBLIC_* vars found in root .env" >&2
fi
