#!/usr/bin/env bash
# Sync NEXT_PUBLIC_* vars from root .env to frontend/.env.local.
#
# Root .env is the single source of truth for ALL services.
# Python services (backend, agent) read root .env directly via Pydantic.
# Only the frontend needs a separate .env.local because Next.js reads
# from its own project root.
#
# Generated file:
#   frontend/.env.local -- frontend vars (NEXT_PUBLIC_*)
set -euo pipefail

ROOT_DIR="$(unset CDPATH; cd "$(dirname "$0")/.." && pwd)"
ROOT_ENV="$ROOT_DIR/.env"
EXAMPLE_ENV="$ROOT_DIR/.env.example"

if [ ! -f "$ROOT_ENV" ]; then
  echo "ERROR: No root .env found. Run: cp .env.example .env" >&2
  exit 1
fi

if [ ! -f "$EXAMPLE_ENV" ]; then
  echo "ERROR: .env.example not found" >&2
  exit 1
fi

HEADER="# AUTO-GENERATED by scripts/sync-env.sh -- do not edit
# Source: root .env ($(date +%Y-%m-%dT%H:%M:%S))
# Edit the root .env and re-run: bash scripts/sync-env.sh"

# Collect frontend keys from @section:frontend in .env.example
frontend_keys=""
in_frontend=false

while IFS= read -r line; do
  if [[ "$line" =~ ^#\ @section:(.+)$ ]]; then
    [[ "${BASH_REMATCH[1]}" == "frontend" ]] && in_frontend=true || in_frontend=false
    continue
  fi
  $in_frontend || continue
  [[ -z "$line" || "$line" =~ ^# ]] && continue
  key="${line%%=*}"
  [[ -n "$key" ]] && frontend_keys="$frontend_keys $key"
done < "$EXAMPLE_ENV"

# Extract matching KEY=VALUE lines from root .env.
extract_vars() {
  local keys="$*"
  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^# ]] && continue
    key="${line%%=*}"
    for k in $keys; do
      if [ "$key" = "$k" ]; then
        echo "$line"
        break
      fi
    done
  done < "$ROOT_ENV"
}

# --- frontend/.env.local ---
{
  echo "$HEADER"
  extract_vars $frontend_keys
} > "$ROOT_DIR/frontend/.env.local"
count=$(grep -cE '^[A-Z_]+=' "$ROOT_DIR/frontend/.env.local" 2>/dev/null || echo 0)

echo "Synced: frontend/.env.local ($count vars)"
