#!/usr/bin/env bash
# Sync root .env to per-service .env files using @section markers from .env.example.
#
# Root .env is the single source of truth. Each service gets only its
# relevant subset (shared + service-specific vars).
#
# Generated files:
#   backend/.env.local  -- shared + backend vars
#   agent/.env.local    -- shared + agent vars
#   frontend/.env.local -- frontend vars (NEXT_PUBLIC_*)
set -euo pipefail

ROOT_DIR="$(unset CDPATH; cd "$(dirname "$0")/.." && pwd)"
ROOT_ENV="$ROOT_DIR/.env"
EXAMPLE_ENV="$ROOT_DIR/.env.example"

if [ ! -f "$ROOT_ENV" ]; then
  echo "ERROR: No root .env found. Run: cp .env.example .env" >&2
  exit 1
fi

if [ ! -f "$EXAMPLE_ENV" ]; then
  echo "ERROR: .env.example not found" >&2
  exit 1
fi

HEADER="# AUTO-GENERATED by scripts/sync-env.sh -- do not edit
# Source: root .env ($(date +%Y-%m-%dT%H:%M:%S))
# Edit the root .env and re-run: npx nx run agentbook:env:sync"

# Build key lists per section from .env.example
shared_keys=""
backend_keys=""
agent_keys=""
frontend_keys=""
current_section=""

while IFS= read -r line; do
  if [[ "$line" =~ ^#\ @section:(.+)$ ]]; then
    current_section="${BASH_REMATCH[1]}"
    continue
  fi
  [[ -z "$line" || "$line" =~ ^# ]] && continue
  key="${line%%=*}"
  [[ -z "$key" ]] && continue
  case "$current_section" in
    shared)   shared_keys="$shared_keys $key" ;;
    backend)  backend_keys="$backend_keys $key" ;;
    agent)    agent_keys="$agent_keys $key" ;;
    frontend) frontend_keys="$frontend_keys $key" ;;
  esac
done < "$EXAMPLE_ENV"

# Extract matching KEY=VALUE lines from root .env for a set of keys.
extract_vars() {
  local keys="$*"
  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^# ]] && continue
    key="${line%%=*}"
    for k in $keys; do
      if [ "$key" = "$k" ]; then
        echo "$line"
        break
      fi
    done
  done < "$ROOT_ENV"
}

# --- backend/.env.local ---
{
  echo "$HEADER"
  extract_vars $shared_keys $backend_keys
} > "$ROOT_DIR/backend/.env.local"
backend_count=$(grep -cE '^[A-Z_]+=' "$ROOT_DIR/backend/.env.local" 2>/dev/null || echo 0)

# --- agent/.env.local ---
{
  echo "$HEADER"
  extract_vars $shared_keys $agent_keys
} > "$ROOT_DIR/agent/.env.local"
agent_count=$(grep -cE '^[A-Z_]+=' "$ROOT_DIR/agent/.env.local" 2>/dev/null || echo 0)

# --- frontend/.env.local ---
{
  echo "$HEADER"
  extract_vars $frontend_keys
} > "$ROOT_DIR/frontend/.env.local"
frontend_count=$(grep -cE '^[A-Z_]+=' "$ROOT_DIR/frontend/.env.local" 2>/dev/null || echo 0)

echo "Synced: backend/.env.local ($backend_count vars), agent/.env.local ($agent_count vars), frontend/.env.local ($frontend_count vars)"
